
  server:
    port: 8081

  spring:
    application:
      name: catalog-service

    kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      consumer:
        group-id: catalog-service
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  management:
    endpoints:
      web:
        exposure:
          include: health,info

  app:
    kafka:
      topics:
        orderCreated: order.created.v1
